### ISSUE TITLE
Control click crashed client when clipboard does not contain plain numbers

### ISSUE THREAD

**Issue by DenL** [chalkos/Marketbuddy#16] opened 2022-05-02 21:48 UTC
### What are you trying to do?

Control click an adjust listing option (by accident) when clipboard does not contain numbers (or empty clipboard?)

### What is the expected behavior?

Program doesn't crash.

### What actually happened?

FFXIV client crashed

### Suggested solution

Not sure what's the expected output here; perhaps throw out an error message and not adjust price listing?

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by xPumaa** [comment] 2022-05-03 00:50
I could not reproduce this with a space, a hexadecimal number or a very long text. Unfortunately, I did not have an empty clipboard and could not test this.

**Comment by chalkos** [comment] 2022-05-03 06:30
the clipboard is not the issue.
```csharp
var cbValue = ImGui.GetClipboardText() ?? "";
if (int.TryParse(cbValue, out var priceValue) && priceValue > 0)
    SetPrice(priceValue);
else
    ChatGui.Print("Marketbuddy: Clipboard does not contain a valid price");
```
any value that is not a positive integer will show an error in the chat.

@DenL do you have Penny Pincher installed?

**Comment by DenL** [comment] 2022-05-03 18:57
I do not. I’ve had it happen a few times when I first opened retainer/marketboard. And control click is the first thing I do.

Apologize for making the false assumption.

Let me play around with it to see how I can reliably reproduce.

**Comment by DenL** [comment] 2022-05-03 18:58
I sometimes have images in my clipboard. Could this happen in that case?

**Comment by xPumaa** [comment] 2022-05-03 20:41
Can confirm. The ImGui.GetClipboardText() function throws an exception with an image in the clipboard.

Fixed with:
```c#
try
{
    var cbValue = ImGui.GetClipboardText() ?? "";
    if (int.TryParse(cbValue, out var priceValue) && priceValue > 0)
        SetPrice(priceValue);
    else
        throw new Exception();
}
catch (Exception)
{
    ChatGui.Print("Marketbuddy: Clipboard does not contain a valid price");
}
```

**Comment by chalkos** [comment] 2022-05-03 23:02
Good find. I'll deploy the fix soon

**Closed** 2022-05-03 23:08 UTC
Labels: bug
